name: SonarCloud TypeScript

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud-typescript:
    uses: 4s1-org/ci-cd-config/.github/workflows/sonarcloud-typescript.yml@main
